const E = '₦500', M = '₦1,000', H = '₦2,000';
const f = (cat, dif, q, a, prize) => ({ category: cat, difficulty: dif, type: 'fitg', question: q, answer: a, option_a: null, option_b: null, option_c: null, option_d: null, prize });
const m = (cat, dif, q, a, oa, ob, oc, od, prize) => ({ category: cat, difficulty: dif, type: 'mcq', question: q, answer: a, option_a: oa, option_b: ob, option_c: oc, option_d: od, prize });

const OG = 'Ogun State Challenge';
const NG = 'Nigeria Challenge';
const SP = 'Sports Challenge';
const MU = 'Music Challenge';
const ST = 'Student Challenge';
const GE = 'Geography Challenge';
const BI = 'Bible Challenge';
const AI = 'AI & Technology';

export const SEED_QUESTIONS = [

  // =============================================
  // OGUN STATE CHALLENGE (100)
  // =============================================
  f(OG,'Easy','The capital of Ogun State is ___','Abeokuta',E),
  f(OG,'Easy','Ogun State is nicknamed the ___ State','Gateway',E),
  f(OG,'Easy','The famous rock monument in Abeokuta is called ___ Rock','Olumo',E),
  f(OG,'Easy','Ogun State was created in the year ___','1976',E),
  f(OG,'Easy','The traditional ruler of the Egba people is called the ___','Alake',E),
  f(OG,'Easy','The Nobel Prize-winning writer from Ogun State is ___','Wole Soyinka',E),
  f(OG,'Easy','The river that gives Ogun State its name is the ___ River','Ogun',E),
  f(OG,'Easy','Covenant University is located in ___, Ogun State','Ota',E),
  f(OG,'Easy','The traditional ruler of the Ijebu kingdom is called the ___','Awujale',E),
  f(OG,'Easy','Ogun State has ___ local government areas','20',E),
  f(OG,'Easy','Ogun State shares a border with the Republic of ___','Benin',E),
  f(OG,'Easy','The state that borders Ogun State to the south is ___ State','Lagos',E),
  f(OG,'Easy','The ___ Festival is celebrated by the Egba people of Ogun State','Lisabi',E),
  f(OG,'Easy','The major border crossing to Benin Republic in Ogun State is at ___','Idiroko',E),
  f(OG,'Easy','Chief Obafemi Awolowo, the famous statesman, was from ___ State','Ogun',E),
  f(OG,'Easy','FUNAAB stands for Federal University of Agriculture, ___','Abeokuta',E),
  f(OG,'Easy','Abeokuta means "___ the rock" in Yoruba','Under',E),
  m(OG,'Easy','What is the capital of Ogun State?','Abeokuta','Sagamu','Abeokuta','Ijebu-Ode','Ota',E),
  m(OG,'Easy','What is the nickname of Ogun State?','Gateway State','Sunshine State','Gateway State','Harmony State','Oil Rivers State',E),
  m(OG,'Easy','Which famous rock formation is found in Abeokuta?','Olumo Rock','Zuma Rock','Gurara Rock','Olumo Rock','Bassa Rock',E),
  m(OG,'Easy','Which Nobel laureate in Literature is from Ogun State?','Wole Soyinka','Chinua Achebe','Ben Okri','Wole Soyinka','Ken Saro-Wiwa',E),
  m(OG,'Easy','In which year was Ogun State created?','1976','1967','1963','1991','1976',E),
  m(OG,'Easy','What is the title of the ruler of the Ijebu kingdom?','Awujale','Alake','Akarigbo','Awujale','Olowu',E),
  m(OG,'Easy','Which university is located in Ota, Ogun State?','Covenant University','Babcock University','Covenant University','Bowen University','Redeemer\'s University',E),
  m(OG,'Easy','Which country shares an international border with Ogun State?','Benin Republic','Ghana','Togo','Benin Republic','Cameroon',E),
  m(OG,'Easy','Which famous statesman from Ogun State was known as "Awo"?','Obafemi Awolowo','Nnamdi Azikiwe','Obafemi Awolowo','Ernest Shonekan','Olusegun Obasanjo',E),
  m(OG,'Easy','What festival do the Egba people of Ogun State celebrate?','Lisabi Festival','Eyo Festival','Argungu Festival','Lisabi Festival','Sango Festival',E),
  m(OG,'Easy','How many local government areas does Ogun State have?','20','16','18','22','20',E),
  m(OG,'Easy','What does "Abeokuta" mean in Yoruba?','Under the rock','City of water','Place of peace','Land of heroes','Under the rock',E),
  m(OG,'Easy','Which state directly borders Ogun State to the south?','Lagos State','Oyo State','Osun State','Ondo State','Lagos State',E),
  m(OG,'Easy','Which border town connects Ogun State to Benin Republic?','Idiroko','Seme','Idiroko','Jibia','Maiyama',E),
  m(OG,'Easy','What is the title of the ruler of the Egba people in Abeokuta?','Alake','Ooni','Alaafin','Alake','Olu',E),
  m(OG,'Easy','Olabisi Onabanjo University is located in which city?','Ago-Iwoye','Abeokuta','Sagamu','Ijebu-Ode','Ago-Iwoye',E),
  m(OG,'Easy','Which Ogun State town hosts a major highway interchange?','Sagamu','Ilaro','Ijebu-Ode','Ota','Sagamu',E),

  f(OG,'Medium','Wole Soyinka won the Nobel Prize in Literature in the year ___','1986',M),
  f(OG,'Medium','The current governor of Ogun State since 2019 is ___','Dapo Abiodun',M),
  f(OG,'Medium','The first civilian governor of Ogun State was ___','Olabisi Onabanjo',M),
  f(OG,'Medium','The British defeated the Ijebu kingdom in the Ijebu Expedition of ___','1892',M),
  f(OG,'Medium','The Egba people migrated and founded Abeokuta in the year ___','1830',M),
  f(OG,'Medium','The traditional ruler of the Remo kingdom is called the ___','Akarigbo',M),
  f(OG,'Medium','Covenant University in Ogun State is owned by the ___ Church','Living Faith',M),
  f(OG,'Medium','Former President Olusegun Obasanjo hails from ___ in Ogun State','Abeokuta',M),
  f(OG,'Medium','The ruler of the Owu kingdom in Ogun State is called the ___','Olowu',M),
  f(OG,'Medium','The state that borders Ogun State to the north is ___ State','Oyo',M),
  f(OG,'Medium','Ogun State was carved out of the old ___ State of Nigeria','Western',M),
  f(OG,'Medium','The town in Ogun State known for the Yewa people is ___','Ilaro',M),
  f(OG,'Medium','The Lagos-Ibadan Expressway passes through which Ogun State city','Sagamu',M),
  f(OG,'Medium','Wole Soyinka\'s play about the Yoruba and colonialism is "Death and the King\'s ___"','Horseman',M),
  f(OG,'Medium','The Lisabi Festival in Ogun State celebrates a warrior hero named ___','Lisabi',M),
  f(OG,'Medium','Ogun State\'s government secretariat complex is at ___','Oke-Mosan',M),
  f(OG,'Medium','The Ijebu people are well known for their trading skills and the ___ cloth','Adire',M),
  m(OG,'Medium','In which year did Wole Soyinka win the Nobel Prize for Literature?','1986','1979','1986','1992','2001',M),
  m(OG,'Medium','Who is the governor of Ogun State as of 2023?','Dapo Abiodun','Ibikunle Amosun','Gbenga Daniel','Dapo Abiodun','Segun Osoba',M),
  m(OG,'Medium','Which church owns Covenant University in Ota?','Living Faith Church','Redeemed Christian Church','Anglican Church','Living Faith Church','Baptist Church',M),
  m(OG,'Medium','Which year was the Ijebu Expedition that brought Ijebu-Ode under British control?','1892','1851','1884','1892','1906',M),
  m(OG,'Medium','In which decade did the Egba people found Abeokuta?','1830s','1800s','1820s','1830s','1850s',M),
  m(OG,'Medium','What is the title of the ruler of the Remo kingdom?','Akarigbo','Awujale','Akarigbo','Alake','Olowu',M),
  m(OG,'Medium','From which old region was Ogun State carved out?','Western State','Eastern State','Western State','North-Central State','Mid-Western State',M),
  m(OG,'Medium','Which former Nigerian President is from Abeokuta, Ogun State?','Olusegun Obasanjo','Sani Abacha','Ibrahim Babangida','Olusegun Obasanjo','Yakubu Gowon',M),
  m(OG,'Medium','What is the title of the ruler of the Owu kingdom in Ogun State?','Olowu','Ooni','Alake','Akarigbo','Olowu',M),
  m(OG,'Medium','Which Ogun State city is the headquarters of the Yewa people?','Ilaro','Abeokuta','Sagamu','Ijebu-Ode','Ilaro',M),
  m(OG,'Medium','Who was the first civilian governor of Ogun State?','Olabisi Onabanjo','Segun Osoba','Gbenga Daniel','Ernest Shonekan','Olabisi Onabanjo',M),
  m(OG,'Medium','Which state borders Ogun State to the north?','Oyo State','Ondo State','Osun State','Oyo State','Ekiti State',M),
  m(OG,'Medium','In what category did Wole Soyinka win the Nobel Prize?','Literature','Peace','Literature','Economics','Medicine',M),
  m(OG,'Medium','Which Nigerian hero from Ogun State led a revolt against Oyo oppressors?','Lisabi','Moremi','Lisabi','Sango','Ogun',M),
  m(OG,'Medium','Which governor of Ogun State served two consecutive terms from 2003 to 2011?','Gbenga Daniel','Segun Osoba','Ibikunle Amosun','Gbenga Daniel','Dapo Abiodun',M),
  m(OG,'Medium','What was the original name of Olabisi Onabanjo University?','Ogun State University','University of Ogun','Remo University','Ogun State University','Gateway University',M),

  f(OG,'Hard','The cement plant in Ewekoro, Ogun State is operated by ___ Cement','Lafarge',H),
  f(OG,'Hard','Babcock University in Ilishan-Remo is owned by the ___ Church','Seventh-day Adventist',H),
  f(OG,'Hard','Wole Soyinka\'s childhood autobiography is titled "Ake: The Years of ___"','Childhood',H),
  f(OG,'Hard','Ogun State\'s industrial zone in Agbara falls under ___ Local Government','Ado-Odo/Ota',H),
  f(OG,'Hard','Ogun State has ___ senatorial districts','3',H),
  f(OG,'Hard','Ogun State has ___ federal constituencies','9',H),
  f(OG,'Hard','The Ijebu Expedition of 1892 was led by British Governor ___','Carter',H),
  f(OG,'Hard','Wole Soyinka\'s debut play performed at Nigerian independence in 1960 was "A Dance of the ___"','Forests',H),
  f(OG,'Hard','Ogun State University was renamed Olabisi Onabanjo University in the year ___','2001',H),
  f(OG,'Hard','Ogun State has ___ members in its State House of Assembly','26',H),
  f(OG,'Hard','The Moshood Abiola Polytechnic is located in ___','Ojere',H),
  f(OG,'Hard','Sagamu is the headquarters of ___ Local Government Area','Sagamu',H),
  f(OG,'Hard','Ogun State\'s coat of arms features ___ Rock at its centre','Olumo',H),
  f(OG,'Hard','The Ogun River originates from the Moshi Hills in ___ State','Oyo',H),
  f(OG,'Hard','Ilaro is the headquarters of ___ Local Government Area','Yewa South',H),
  f(OG,'Hard','The famous Kuto market in Abeokuta is located near the ___ train station','Abeokuta',H),
  m(OG,'Hard','What was the name of Wole Soyinka\'s debut play in 1960?','A Dance of the Forests','Death and the King\'s Horseman','The Road','A Dance of the Forests','The Lion and the Jewel',H),
  m(OG,'Hard','Which cement company operates in Ewekoro, Ogun State?','Lafarge','Dangote','BUA','Lafarge','Unicem',H),
  m(OG,'Hard','Babcock University in Ilishan-Remo is owned by which church?','Seventh-day Adventist Church','Catholic Church','Anglican Church','Seventh-day Adventist Church','Methodist Church',H),
  m(OG,'Hard','What is the title of Wole Soyinka\'s childhood autobiography?','Ake: The Years of Childhood','Ibadan: The Penkelemes Years','You Must Set Forth at Dawn','Ake: The Years of Childhood','Seasons of Anomy',H),
  m(OG,'Hard','What is the name of the government secretariat complex in Abeokuta?','Oke-Mosan','Ita-Eko','Oke-Mosan','Ibara','Kemta',H),
  m(OG,'Hard','Who led the British Ijebu Expedition of 1892?','Governor Carter','Lord Lugard','Governor Carter','General Glover','Governor McCallum',H),
  m(OG,'Hard','How many senatorial districts does Ogun State have?','3','2','3','4','5',H),
  m(OG,'Hard','Which local government area contains the Agbara industrial zone?','Ado-Odo/Ota','Sagamu','Ijebu-Ode','Ado-Odo/Ota','Obafemi Owode',H),
  m(OG,'Hard','What is the Egba warrior hero celebrated at the Lisabi Festival called?','Lisabi Agbongbo-Akala','Moremi Ajasoro','Lisabi Agbongbo-Akala','Oduduwa','Sango',H),
  m(OG,'Hard','How many federal constituencies does Ogun State have?','9','6','7','9','12',H),
  m(OG,'Hard','In which year was Olabisi Onabanjo University formally renamed?','2001','1995','1998','2001','2005',H),
  m(OG,'Hard','How many members sit in the Ogun State House of Assembly?','26','20','24','26','32',H),
  m(OG,'Hard','Where does the Ogun River originate?','Oyo State','Ogun State','Ekiti State','Oyo State','Ondo State',H),
  m(OG,'Hard','Which Ogun State governor served between 2011 and 2019?','Ibikunle Amosun','Segun Osoba','Gbenga Daniel','Ibikunle Amosun','Dapo Abiodun',H),

  // =============================================
  // NIGERIA CHALLENGE (100)
  // =============================================
  f(NG,'Easy','The capital of Nigeria is ___','Abuja',E),
  f(NG,'Easy','Nigeria gained independence on October 1, ___','1960',E),
  f(NG,'Easy','The official language of Nigeria is ___','English',E),
  f(NG,'Easy','The Nigerian currency is called the ___','Naira',E),
  f(NG,'Easy','Nigeria has ___ states and a Federal Capital Territory','36',E),
  f(NG,'Easy','The largest city in Nigeria by population is ___','Lagos',E),
  f(NG,'Easy','Nigeria\'s two major rivers are the Niger and ___','Benue',E),
  f(NG,'Easy','The Nigerian national football team is called the Super ___','Eagles',E),
  f(NG,'Easy','Nigeria became a republic in ___','1963',E),
  f(NG,'Easy','The first Prime Minister of Nigeria was ___','Tafawa Balewa',E),
  f(NG,'Easy','The Nigerian flag has two colours: ___ and white','Green',E),
  f(NG,'Easy','Nigeria is the most ___ country in Africa','populous',E),
  f(NG,'Easy','The three largest ethnic groups in Nigeria are Yoruba, Igbo, and ___','Hausa',E),
  f(NG,'Easy','The naira symbol is ___','₦',E),
  f(NG,'Easy','Nigeria is located in ___ Africa','West',E),
  f(NG,'Easy','The first Nigerian to win a Nobel Prize was ___','Wole Soyinka',E),
  f(NG,'Easy','Nigeria\'s national anthem begins with "Arise O ___"','Compatriots',E),
  m(NG,'Easy','What is the capital of Nigeria?','Abuja','Lagos','Abuja','Kano','Ibadan',E),
  m(NG,'Easy','When did Nigeria gain independence?','October 1, 1960','October 1, 1956','October 1, 1960','January 1, 1960','October 1, 1963',E),
  m(NG,'Easy','What is the official language of Nigeria?','English','Yoruba','Igbo','English','Hausa',E),
  m(NG,'Easy','What is Nigeria\'s currency?','Naira','Cedi','Pound','Dollar','Naira',E),
  m(NG,'Easy','How many states does Nigeria have?','36','30','32','36','38',E),
  m(NG,'Easy','Which is the largest city in Nigeria?','Lagos','Abuja','Lagos','Kano','Port Harcourt',E),
  m(NG,'Easy','What are Nigeria\'s two major rivers?','Niger and Benue','Niger and Ogun','Niger and Benue','Benue and Kaduna','Niger and Volta',E),
  m(NG,'Easy','What is Nigeria\'s national football team called?','Super Eagles','The Lions','Super Eagles','The Warriors','The Elephants',E),
  m(NG,'Easy','Nigeria became a republic in which year?','1963','1960','1963','1966','1979',E),
  m(NG,'Easy','Who was Nigeria\'s first Prime Minister?','Tafawa Balewa','Nnamdi Azikiwe','Ahmadu Bello','Tafawa Balewa','Obafemi Awolowo',E),
  m(NG,'Easy','What colours are on Nigeria\'s flag?','Green and white','Red and white','Blue and white','Green and white','Yellow and green',E),
  m(NG,'Easy','Which continent is Nigeria in?','Africa','Asia','Europe','South America','Africa',E),
  m(NG,'Easy','Who was the first Nigerian to win a Nobel Prize?','Wole Soyinka','Chinua Achebe','Ben Okri','Wole Soyinka','Ngugi wa Thiong\'o',E),
  m(NG,'Easy','Nigeria\'s largest ethnic group is?','Hausa-Fulani','Yoruba','Igbo','Hausa-Fulani','Tiv',E),
  m(NG,'Easy','What region of Africa is Nigeria located in?','West Africa','East Africa','North Africa','Southern Africa','West Africa',E),
  m(NG,'Easy','Nigeria\'s national anthem starts with "Arise O ___"','Compatriots','Nigerians','Citizens','Compatriots','Countrymen',E),

  f(NG,'Medium','Nigeria\'s civil war lasted from 1967 to ___','1970',M),
  f(NG,'Medium','Oil was first discovered in Nigeria in 1956 at ___','Oloibiri',M),
  f(NG,'Medium','The first President of Nigeria was ___','Nnamdi Azikiwe',M),
  f(NG,'Medium','Nigeria\'s Fourth Republic constitution came into force in ___','1999',M),
  f(NG,'Medium','The federal capital was moved from Lagos to Abuja in ___','1991',M),
  f(NG,'Medium','Nigeria was formally amalgamated by Frederick Lugard in ___','1914',M),
  f(NG,'Medium','Nigeria\'s major oil-producing region is the ___ Delta','Niger',M),
  f(NG,'Medium','The ___ Bridge in Lagos is Nigeria\'s longest bridge','Third Mainland',M),
  f(NG,'Medium','Nigeria joined the United Nations in ___','1960',M),
  f(NG,'Medium','ECOWAS headquarters is located in ___','Abuja',M),
  f(NG,'Medium','The Nigerian Stock Exchange is located in ___','Lagos',M),
  f(NG,'Medium','NNPC stands for Nigerian National ___ Corporation','Petroleum',M),
  f(NG,'Medium','Nigeria\'s first military coup took place in ___','1966',M),
  f(NG,'Medium','The naira replaced the Nigerian pound on January 1, ___','1973',M),
  f(NG,'Medium','Nigeria has ___ geopolitical zones','6',M),
  f(NG,'Medium','Nigeria\'s total number of local government areas is ___','774',M),
  f(NG,'Medium','The University of Ibadan, Nigeria\'s first university, was founded in ___','1948',M),
  m(NG,'Medium','When did Nigeria\'s civil war end?','1970','1968','1970','1972','1975',M),
  m(NG,'Medium','Where was oil first discovered in Nigeria?','Oloibiri','Port Harcourt','Warri','Oloibiri','Calabar',M),
  m(NG,'Medium','Who was Nigeria\'s first President?','Nnamdi Azikiwe','Tafawa Balewa','Nnamdi Azikiwe','Obafemi Awolowo','Ahmadu Bello',M),
  m(NG,'Medium','When was Nigeria\'s Fourth Republic constitution enacted?','1999','1979','1993','1999','2003',M),
  m(NG,'Medium','When was Nigeria formally amalgamated?','1914','1900','1906','1914','1922',M),
  m(NG,'Medium','When did Nigeria\'s federal capital officially move to Abuja?','1991','1976','1986','1991','1999',M),
  m(NG,'Medium','When was the Nigerian naira introduced?','1973','1960','1966','1973','1979',M),
  m(NG,'Medium','Where is ECOWAS headquartered?','Abuja','Accra','Lagos','Abuja','Dakar',M),
  m(NG,'Medium','What is the longest bridge in Nigeria?','Third Mainland Bridge','Carter Bridge','Eko Bridge','Third Mainland Bridge','Lagos Bridge',M),
  m(NG,'Medium','When did Nigeria join the United Nations?','1960','1960','1963','1965','1967',M),
  m(NG,'Medium','What does NNPC stand for?','Nigerian National Petroleum Corporation','Nigerian National Petroleum Corporation','Nigerian National Power Company','National Network Petroleum Council','National Naira Price Control',M),
  m(NG,'Medium','How many geopolitical zones does Nigeria have?','6','4','5','6','7',M),
  m(NG,'Medium','How many local government areas does Nigeria have?','774','680','774','800','850',M),
  m(NG,'Medium','When was the University of Ibadan founded?','1948','1936','1942','1948','1955',M),

  f(NG,'Hard','Nigeria has ___ senators in the National Assembly','109',H),
  f(NG,'Hard','Nigeria\'s House of Representatives has ___ members','360',H),
  f(NG,'Hard','Nigeria won its first Olympic gold medal in football at the ___ Olympics','1996 Atlanta',H),
  f(NG,'Hard','The EFCC was established in ___','2003',H),
  f(NG,'Hard','ECOWAS was established in ___','1975',H),
  f(NG,'Hard','The Benin Bronzes were seized by the British in the ___ Expedition','1897',H),
  f(NG,'Hard','Nigeria\'s Kainji Dam is built on the ___ River','Niger',H),
  f(NG,'Hard','Military head of state Murtala Mohammed was assassinated in ___','1976',H),
  f(NG,'Hard','Nigeria first won the Africa Cup of Nations in ___','1980',H),
  f(NG,'Hard','Nigeria\'s first election under colonial rule was held in ___','1923',H),
  f(NG,'Hard','Nigeria\'s Chief Justice heads the ___ Court','Supreme',H),
  f(NG,'Hard','Nigeria has approximately ___ sq km of land area','924,000',H),
  f(NG,'Hard','The Federal Road Safety Corps was established in ___','1988',H),
  f(NG,'Hard','Nigeria\'s first AFCON title was hosted in ___','Lagos',H),
  f(NG,'Hard','The 1954 ___ Constitution introduced a federal system to Nigeria','Lyttleton',H),
  f(NG,'Hard','Aliko Dangote, Africa\'s richest person, is from ___ State','Kano',H),
  m(NG,'Hard','How many senators are in Nigeria\'s National Assembly?','109','100','109','120','360',H),
  m(NG,'Hard','How many members does Nigeria\'s House of Representatives have?','360','250','300','360','400',H),
  m(NG,'Hard','At which Olympics did Nigeria win its first football gold medal?','1996 Atlanta','1984 Los Angeles','1988 Seoul','1992 Barcelona','1996 Atlanta',H),
  m(NG,'Hard','When was the EFCC established?','2003','1999','2001','2003','2007',H),
  m(NG,'Hard','When was ECOWAS established?','1975','1960','1970','1975','1985',H),
  m(NG,'Hard','In what year were the Benin Bronzes seized by the British?','1897','1881','1897','1902','1914',H),
  m(NG,'Hard','Which river is the Kainji Dam built on?','Niger River','Benue River','Niger River','Kaduna River','Ogun River',H),
  m(NG,'Hard','When was Murtala Mohammed assassinated?','1976','1975','1976','1977','1979',H),
  m(NG,'Hard','When did Nigeria first win the Africa Cup of Nations?','1980','1976','1978','1980','1984',H),
  m(NG,'Hard','How many LGAs does Nigeria have?','774','680','720','774','850',H),
  m(NG,'Hard','Which state is Aliko Dangote from?','Kano','Lagos','Kaduna','Kano','Sokoto',H),
  m(NG,'Hard','The 1954 Constitution that introduced federalism to Nigeria is named after?','Lyttleton','Richards','Macpherson','Lyttleton','Clifford',H),
  m(NG,'Hard','Where was Nigeria\'s first AFCON tournament hosted?','Lagos','Accra','Cairo','Lagos','Dakar',H),
  m(NG,'Hard','When was the Federal Road Safety Corps of Nigeria established?','1988','1978','1982','1988','1993',H),
  m(NG,'Hard','Nigeria\'s Supreme Court is headed by which official?','Chief Justice','President','Attorney General','Chief Justice','Speaker',H),
  m(NG,'Hard','In which year was Nigeria\'s first colonial election held?','1923','1914','1920','1923','1930',H),

  // =============================================
  // SPORTS CHALLENGE (100)
  // =============================================
  f(SP,'Easy','Nigeria\'s national football team is called the Super ___','Eagles',E),
  f(SP,'Easy','Nigeria first won the Africa Cup of Nations in ___','1980',E),
  f(SP,'Easy','Nigerian footballer Austin Okocha is known by the nickname ___','Jay-Jay',E),
  f(SP,'Easy','Nwankwo Kanu won the Champions League with ___ in 1995','Ajax',E),
  f(SP,'Easy','Nigeria qualified for its first FIFA World Cup in ___','1994',E),
  f(SP,'Easy','The Olympic Games are held every ___ years','4',E),
  f(SP,'Easy','Rashidi Yekini scored Nigeria\'s first World Cup goal against ___','Bulgaria',E),
  f(SP,'Easy','A score of 40-40 in tennis is called ___','Deuce',E),
  f(SP,'Easy','A batsman scoring 100 runs in cricket is called a ___','Century',E),
  f(SP,'Easy','Lionel Messi represents ___ national team','Argentina',E),
  f(SP,'Easy','Usain Bolt is the fastest man in history from ___','Jamaica',E),
  f(SP,'Easy','A hat-trick in football means scoring ___ goals in one match','three',E),
  f(SP,'Easy','Nigeria won the Olympic gold medal in football at the ___ Olympics','Atlanta 1996',E),
  f(SP,'Easy','The sport played at Wimbledon is ___','Tennis',E),
  f(SP,'Easy','Brazil has won the FIFA World Cup ___ times','5',E),
  f(SP,'Easy','Cristiano Ronaldo plays for ___ national team','Portugal',E),
  f(SP,'Easy','Nigeria\'s women\'s football team is called the Super ___','Falcons',E),
  m(SP,'Easy','What is Nigeria\'s national football team called?','Super Eagles','Black Stars','Super Eagles','Warriors','Lions',E),
  m(SP,'Easy','Who is known as "Jay-Jay" in Nigerian football?','Austin Okocha','Nwankwo Kanu','Rashidi Yekini','Austin Okocha','John Obi Mikel',E),
  m(SP,'Easy','Which club did Kanu win the Champions League with in 1995?','Ajax','Barcelona','AC Milan','Ajax','Real Madrid',E),
  m(SP,'Easy','When did Nigeria first qualify for the FIFA World Cup?','1994','1990','1994','1998','2002',E),
  m(SP,'Easy','How often are the Olympic Games held?','Every 4 years','Every 2 years','Every 3 years','Every 4 years','Every 5 years',E),
  m(SP,'Easy','What is a score of 40-40 called in tennis?','Deuce','Fault','Deuce','Tie-break','Love',E),
  m(SP,'Easy','Who is the fastest man in history?','Usain Bolt','Maurice Greene','Carl Lewis','Usain Bolt','Justin Gatlin',E),
  m(SP,'Easy','What is it called when a batsman scores 100 runs in cricket?','Century','Six','Double','Century','Run out',E),
  m(SP,'Easy','At which Olympics did Nigeria win football gold?','1996 Atlanta','1992 Barcelona','1996 Atlanta','2000 Sydney','2004 Athens',E),
  m(SP,'Easy','What sport is played at Wimbledon?','Tennis','Cricket','Rugby','Tennis','Badminton',E),
  m(SP,'Easy','How many times has Brazil won the FIFA World Cup?','5','3','4','5','6',E),
  m(SP,'Easy','What country does Cristiano Ronaldo represent?','Portugal','Spain','Brazil','France','Portugal',E),
  m(SP,'Easy','What is Nigeria\'s women\'s national football team called?','Super Falcons','Super Eagles B','Lady Eagles','Super Falcons','Golden Goddesses',E),
  m(SP,'Easy','Against which country did Rashidi Yekini score Nigeria\'s first World Cup goal?','Bulgaria','Cameroon','Bulgaria','Argentina','Italy',E),
  m(SP,'Easy','What is a hat-trick in football?','Scoring 3 goals','Scoring 2 goals','Scoring 3 goals','Scoring 4 goals','A type of free kick',E),

  f(SP,'Medium','Nigeria won the AFCON for the third time in ___','2013',M),
  f(SP,'Medium','Nigeria\'s women\'s football team won the African Women Cup of Nations ___ consecutive times from 1998 to 2010','7',M),
  f(SP,'Medium','Jay-Jay Okocha played for ___ FC in France','Paris Saint-Germain',M),
  f(SP,'Medium','John Obi Mikel played for ___ FC in England','Chelsea',M),
  f(SP,'Medium','Nigeria\'s highest FIFA ranking was ___ in 1994','5th',M),
  f(SP,'Medium','Nigerian boxer Dick Tiger was world champion at ___ weight','Middleweight',M),
  f(SP,'Medium','The 2013 AFCON tournament was held in ___','South Africa',M),
  f(SP,'Medium','Odion Ighalo was Nigeria\'s top scorer at the 2019 ___','AFCON',M),
  f(SP,'Medium','Victor Moses played as ___ for Chelsea FC','wing-back',M),
  f(SP,'Medium','Nwankwo Kanu scored 3 goals in 15 minutes for Arsenal as a substitute against ___ in the FA Cup','Sheffield United',M),
  f(SP,'Medium','Nigeria beat Argentina ___ in the 1996 Olympic final','3-2',M),
  f(SP,'Medium','Ahmed Musa scored two goals against ___ at the 2018 World Cup','Iceland',M),
  f(SP,'Medium','Victor Osimhen plays for ___ in Italy','Napoli',M),
  f(SP,'Medium','Nigeria has qualified for the FIFA World Cup ___ times as of 2022','6',M),
  f(SP,'Medium','Nwankwo Kanu won the ___ Ball award at the 1996 Olympics','Golden',M),
  f(SP,'Medium','Wilfred Ndidi plays as ___ midfielder for Leicester City','defensive',M),
  f(SP,'Medium','The Nigerian sprinter Tobi Amusan became world champion in the ___ hurdles in 2022','100m',M),
  m(SP,'Medium','How many times has Nigeria won the Africa Cup of Nations?','3','2','3','4','5',M),
  m(SP,'Medium','Who was Nigeria\'s top scorer at the 2019 AFCON?','Odion Ighalo','Victor Moses','Odion Ighalo','Kelechi Iheanacho','Ahmed Musa',M),
  m(SP,'Medium','Which club did John Obi Mikel play for in England?','Chelsea','Arsenal','Chelsea','Manchester City','Tottenham',M),
  m(SP,'Medium','Where was the 2013 AFCON held?','South Africa','Ghana','Nigeria','South Africa','Egypt',M),
  m(SP,'Medium','What weight class was Dick Tiger world champion in?','Middleweight','Heavyweight','Middleweight','Lightweight','Featherweight',M),
  m(SP,'Medium','What was Nigeria\'s highest-ever FIFA ranking?','5th','8th','5th','10th','15th',M),
  m(SP,'Medium','Against which country did Ahmed Musa score twice at the 2018 World Cup?','Iceland','Croatia','Iceland','Argentina','Brazil',M),
  m(SP,'Medium','What position does Victor Osimhen play?','Striker','Goalkeeper','Defender','Midfielder','Striker',M),
  m(SP,'Medium','What award did Nwankwo Kanu win at the 1996 Olympics?','Golden Ball','Golden Boot','Golden Glove','Golden Ball','Fair Play Award',M),
  m(SP,'Medium','Which Nigerian played for Paris Saint-Germain?','Jay-Jay Okocha','Nwankwo Kanu','Jay-Jay Okocha','John Obi Mikel','Odion Ighalo',M),
  m(SP,'Medium','Nigeria beat Argentina ___ in the 1996 Olympic football final','3-2','2-1','3-2','3-1','2-0',M),
  m(SP,'Medium','What position does Wilfred Ndidi play?','Defensive midfielder','Striker','Winger','Defensive midfielder','Goalkeeper',M),
  m(SP,'Medium','Victor Moses played what position for Chelsea?','Wing-back','Striker','Centre midfielder','Wing-back','Goalkeeper',M),
  m(SP,'Medium','How many times has Nigeria qualified for the FIFA World Cup?','6','4','5','6','7',M),
  m(SP,'Medium','Which Nigerian club is based in Kano?','Kano Pillars','Enyimba FC','Rangers FC','Kano Pillars','Shooting Stars',M),

  f(SP,'Hard','Nigeria\'s first AFCON title was held in Lagos at the ___ Stadium','National',H),
  f(SP,'Hard','The Super Eagles coach who led Nigeria to win the 2013 AFCON was ___','Stephen Keshi',H),
  f(SP,'Hard','Nigeria was eliminated from the 1994 World Cup by ___ in the Round of 16','Italy',H),
  f(SP,'Hard','Nigeria won the FIFA Under-17 World Cup for the first time in ___','1985',H),
  f(SP,'Hard','Celestine Babayaro played at ___ back for Nigeria at the 1996 Olympics','left',H),
  f(SP,'Hard','Nigeria\'s football governing body is called the ___ Football Federation','Nigeria',H),
  f(SP,'Hard','The Nigeria vs Italy score at the 1994 World Cup Round of 16 was ___','2-1 to Italy',H),
  f(SP,'Hard','Super Falcons captain Asisat Oshoala plays as a ___','striker',H),
  f(SP,'Hard','Nigeria first beat Argentina at the 1994 World Cup group stage ___ to ___','1-0',H),
  f(SP,'Hard','The record attendance at a Nigerian league match was at the ___ Stadium','National',H),
  f(SP,'Hard','Nigerian sprinter Blessing Okagbare also competes in the ___','long jump',H),
  f(SP,'Hard','The NFF was founded in ___','1945',H),
  f(SP,'Hard','Nigeria won bronze at the ___ Africa Cup of Nations in 2019','AFCON',H),
  f(SP,'Hard','Enyimba FC is based in ___ State','Abia',H),
  f(SP,'Hard','The first Nigerian to play in the English Premier League was ___','Efan Ekoku',H),
  f(SP,'Hard','Nwankwo Kanu scored a famous hat-trick against Chelsea from ___-0 down in the FA Cup','2',H),
  m(SP,'Hard','Which coach led Nigeria to win the 2013 AFCON?','Stephen Keshi','Shuaibu Amodu','Lars Lagerback','Stephen Keshi','Gernot Rohr',H),
  m(SP,'Hard','Which country eliminated Nigeria from the 1994 World Cup?','Italy','Brazil','Greece','Italy','Spain',H),
  m(SP,'Hard','When did Nigeria first win the FIFA U-17 World Cup?','1985','1983','1985','1987','1989',H),
  m(SP,'Hard','What position does Asisat Oshoala play?','Striker','Goalkeeper','Defender','Midfielder','Striker',H),
  m(SP,'Hard','Which state is Enyimba FC based in?','Abia State','Enugu State','Abia State','Anambra State','Lagos State',H),
  m(SP,'Hard','Who was the first Nigerian to play in the English Premier League?','Efan Ekoku','Nwankwo Kanu','Jay-Jay Okocha','Efan Ekoku','Sunday Oliseh',H),
  m(SP,'Hard','In what year was the NFF (Nigeria Football Federation) founded?','1945','1935','1940','1945','1950',H),
  m(SP,'Hard','Against which club did Kanu score his famous FA Cup hat-trick from 2-0 down?','Sheffield United','Chelsea','Arsenal','Sheffield United','Tottenham',H),
  m(SP,'Hard','Nigeria won what position at the 2019 AFCON?','Bronze (3rd place)','Gold','Silver','Bronze (3rd place)','4th place',H),
  m(SP,'Hard','What other event does Blessing Okagbare compete in besides sprinting?','Long jump','Javelin','Long jump','High jump','Shot put',H),
  m(SP,'Hard','What was the score when Nigeria beat Argentina in the 1994 World Cup group stage?','1-0','2-1','1-0','3-2','2-0',H),
  m(SP,'Hard','Which Nigerian won the 100m hurdles world championship in 2022?','Tobi Amusan','Blessing Okagbare','Ese Brume','Tobi Amusan','Falilat Ogunkoya',H),
  m(SP,'Hard','How many times has Nigeria won the Africa Women Cup of Nations as of 2023?','11','7','9','11','13',H),
  m(SP,'Hard','Against which country did Nigeria win their first-ever World Cup match in 1994?','Bulgaria','Bulgaria','Greece','Argentina','Italy',H),

  // =============================================
  // MUSIC CHALLENGE (100)
  // =============================================
  f(MU,'Easy','The genre of music associated with Nigerian artists like Wizkid and Davido is called ___','Afrobeats',E),
  f(MU,'Easy','Wizkid\'s full name is Ayodeji ___ Balogun','Ibrahim',E),
  f(MU,'Easy','The Nigerian music legend known as the "King of Juju Music" is ___','King Sunny Ade',E),
  f(MU,'Easy','Burna Boy\'s real name is Damini Ebunoluwa ___','Ogulu',E),
  f(MU,'Easy','The famous Nigerian musician and activist known as "Abami Eda" was ___','Fela Kuti',E),
  f(MU,'Easy','Michael Jackson was known as the King of ___','Pop',E),
  f(MU,'Easy','The music streaming platform owned by Apple is called Apple ___','Music',E),
  f(MU,'Easy','A Grammy Award is given for excellence in the ___ industry','music',E),
  f(MU,'Easy','Bob Marley was a musician from ___','Jamaica',E),
  f(MU,'Easy','Tiwa Savage is known as the Queen of ___','Afrobeats',E),
  f(MU,'Easy','Davido\'s record label is called DMW which stands for Davido Music ___','Worldwide',E),
  f(MU,'Easy','The Grammys are hosted annually in the ___','United States',E),
  f(MU,'Easy','Wizkid\'s breakthrough hit song was "Holla at Your ___"','Boy',E),
  f(MU,'Easy','The music genre that blends reggae with African rhythms is called ___','Afrobeats',E),
  f(MU,'Easy','Rema\'s real name is Divine Ikubor and he is from ___ State','Edo',E),
  f(MU,'Easy','Taylor Swift is known for playing the guitar and writing ___','songs',E),
  f(MU,'Easy','Drake is a rapper and singer from ___','Canada',E),
  m(MU,'Easy','What genre of music is Wizkid most known for?','Afrobeats','Hip-hop','Reggae','Afrobeats','Classical',E),
  m(MU,'Easy','Who is known as the King of Juju Music?','King Sunny Ade','Fela Kuti','Ebenezer Obey','King Sunny Ade','Haruna Ishola',E),
  m(MU,'Easy','What is Burna Boy\'s real first name?','Damini','Ayodeji','Chukwuebuka','Damini','Daniel',E),
  m(MU,'Easy','What was Fela Kuti\'s nickname?','Abami Eda','King of Pop','Baba 70','Abami Eda','The Legend',E),
  m(MU,'Easy','What is Michael Jackson known as?','King of Pop','King of Pop','King of Soul','King of Rock','King of Afrobeats',E),
  m(MU,'Easy','Where is Bob Marley from?','Jamaica','Ghana','Cuba','Nigeria','Jamaica',E),
  m(MU,'Easy','Who is known as the Queen of Afrobeats?','Tiwa Savage','Yemi Alade','Simi','Tiwa Savage','Davido',E),
  m(MU,'Easy','What does DMW stand for?','Davido Music Worldwide','David Music World','Davido Music Worldwide','DM Works','Davido\'s Music Works',E),
  m(MU,'Easy','Who released the song "Essence" featuring Tems?','Wizkid','Davido','Burna Boy','Wizkid','Rema',E),
  m(MU,'Easy','What country is Drake from?','Canada','USA','UK','Canada','Jamaica',E),
  m(MU,'Easy','What is Rema\'s real name?','Divine Ikubor','Damini Ogulu','Divine Ikubor','Ayodeji Balogun','David Adeleke',E),
  m(MU,'Easy','Wizkid\'s breakthrough song was?','Holla at Your Boy','Ojuelegba','Holla at Your Boy','Essence','Soco',E),
  m(MU,'Easy','Which state is Rema from?','Edo State','Lagos State','Edo State','Rivers State','Ogun State',E),
  m(MU,'Easy','Which award ceremony is considered the most prestigious in music?','Grammy Awards','BET Awards','MTV VMAs','Grammy Awards','MOBO Awards',E),

  f(MU,'Medium','Burna Boy won a Grammy Award for Best Global Music Album for ___','Twice as Tall',M),
  f(MU,'Medium','Wizkid\'s album "Made in Lagos" was released in ___','2020',M),
  f(MU,'Medium','Davido\'s real name is David ___ Adeleke','Adedeji',M),
  f(MU,'Medium','Fela Kuti\'s genre of music is called ___','Afrobeat',M),
  f(MU,'Medium','Yemi Alade is known as Mama ___','Africa',M),
  f(MU,'Medium','The Nigerian boy band that rose to fame in the 2010s is called P-___','Square',M),
  f(MU,'Medium','Tems\'s full name is Temilade Openiyi and she is from ___ State','Lagos',M),
  f(MU,'Medium','Afrobeats producer Don Jazzy\'s real name is Michael ___ Collins','Ajereh',M),
  f(MU,'Medium','Wizkid\'s record label is called Starboy ___','Entertainment',M),
  f(MU,'Medium','Asa is a Nigerian singer known for blending Afropop with ___','soul',M),
  f(MU,'Medium','The Nigerian reggae/dancehall artist known as "Mr. Endowed" is ___','Patoranking',M),
  f(MU,'Medium','Burna Boy\'s studio album "African Giant" was released in ___','2019',M),
  f(MU,'Medium','2Face Idibia\'s real name is Innocent ___ Idibia','Ujah',M),
  f(MU,'Medium','The Nigerian music label Mavin Records was founded by ___','Don Jazzy',M),
  f(MU,'Medium','Olamide Adedeji is known as the YBNL King and his nickname is ___','Baddo',M),
  f(MU,'Medium','The Afrobeats artist Ckay\'s song "Love Nwantiti" went viral in ___','2021',M),
  f(MU,'Medium','Joeboy\'s hit song "Beginning" was produced by ___','Killertunes',M),
  m(MU,'Medium','Which album won Burna Boy his first Grammy?','Twice as Tall','African Giant','Love Damini','Twice as Tall','Outside',M),
  m(MU,'Medium','When was Wizkid\'s "Made in Lagos" album released?','2020','2018','2019','2020','2021',M),
  m(MU,'Medium','What is Davido\'s real name?','David Adedeji Adeleke','David Okonkwo','David Adedeji Adeleke','Daniel Adeleke','Davide Adeleke',M),
  m(MU,'Medium','What genre did Fela Kuti create?','Afrobeat','Afrobeats','Juju','Afrobeat','Fuji',M),
  m(MU,'Medium','What is Yemi Alade known as?','Mama Africa','Queen of Afrobeats','Mama Africa','African Princess','Lady Afro',M),
  m(MU,'Medium','Who founded Mavin Records?','Don Jazzy','Davido','Wizkid','Don Jazzy','2face',M),
  m(MU,'Medium','What is 2Face Idibia\'s real first name?','Innocent','Chukwuemeka','Innocent','Obinna','Tunde',M),
  m(MU,'Medium','What is Patoranking\'s nickname?','Mr. Endowed','Baddo','Mr. Endowed','The King','Oga',M),
  m(MU,'Medium','Which Nigerian music label did Tiwa Savage sign with internationally?','Universal Music Group','Sony Music','Warner Music','Universal Music Group','Atlantic Records',M),
  m(MU,'Medium','What is Don Jazzy\'s real name?','Michael Ajereh','Michael Collins','Michael Ajereh','Don Johnson','Jazzy Michael',M),
  m(MU,'Medium','What is Olamide\'s nickname?','Baddo','Mr. Endowed','Baddo','Baddest','Baba',M),
  m(MU,'Medium','Ckay\'s viral song "Love Nwantiti" took off globally in which year?','2021','2019','2020','2021','2022',M),
  m(MU,'Medium','P-Square is composed of which two brothers?','Peter and Paul Okoye','Emeka and Chidi Okoye','Peter and Paul Okoye','Tunde and Kehinde Balogun','Taiwo and Kehinde Okoye',M),
  m(MU,'Medium','What state is Tems from?','Lagos State','Ogun State','Lagos State','Delta State','Rivers State',M),

  f(MU,'Hard','Fela Kuti\'s most politically charged album was "Zombie" released in ___','1977',H),
  f(MU,'Hard','Burna Boy\'s Grammy-winning album "Twice as Tall" was co-produced by ___','Diddy',H),
  f(MU,'Hard','The 2022 Grammy for Best Global Music Performance was won by Wizkid for ___','Essence',H),
  f(MU,'Hard','Tems won a Grammy in 2023 for Best African Music Performance for "Free ___"','Mind',H),
  f(MU,'Hard','King Sunny Ade was nominated for a Grammy in ___','1983',H),
  f(MU,'Hard','Fela Kuti\'s Afrika Shrine was founded in ___','1970',H),
  f(MU,'Hard','Yemi Alade\'s debut album was called "King of Queens" released in ___','2014',H),
  f(MU,'Hard','The song "FEM" by Davido topped Nigerian charts in ___','2020',H),
  f(MU,'Hard','Wizkid became the first African artist to have a number-one song on the Billboard ___ chart','Afrobeats',H),
  f(MU,'Hard','Burna Boy\'s first studio album was called "___" released in 2013','L.I.F.E.',H),
  f(MU,'Hard','Tiwa Savage\'s debut album "Once Upon a Time" was released in ___','2013',H),
  f(MU,'Hard','The first Nigerian artist to sell out the O2 Arena in London was ___','Davido',H),
  f(MU,'Hard','Afrobeats producer Sarz\'s real name is Osaretin ___','Ighodaro',H),
  f(MU,'Hard','The music collective called YBNL Nation was founded by ___','Olamide',H),
  f(MU,'Hard','Fireboy DML\'s real name is Adedamola Adefolahan and he is signed to ___','YBNL',H),
  f(MU,'Hard','Rema\'s hit "Calm Down" broke the record for most weeks on the ___ Afrobeats chart','Billboard',H),
  m(MU,'Hard','When was Fela Kuti\'s album "Zombie" released?','1977','1972','1975','1977','1980',H),
  m(MU,'Hard','Who co-produced Burna Boy\'s Grammy-winning album?','Diddy','Dr. Dre','Diddy','Timbaland','Pharrell',H),
  m(MU,'Hard','What song won Wizkid a Grammy in 2022?','Essence','Ojuelegba','Essence','Soco','Made in Lagos',H),
  m(MU,'Hard','What Grammy did Tems win in 2023?','Best African Music Performance','Best New Artist','Best African Music Performance','Best Global Album','Best R&B Song',H),
  m(MU,'Hard','When was King Sunny Ade Grammy-nominated?','1983','1980','1983','1987','1990',H),
  m(MU,'Hard','When did Fela Kuti found his Afrika Shrine?','1970','1965','1970','1975','1980',H),
  m(MU,'Hard','When was Tiwa Savage\'s debut album released?','2013','2011','2012','2013','2015',H),
  m(MU,'Hard','Who was the first Nigerian artist to sell out the O2 Arena?','Davido','Wizkid','Burna Boy','Davido','2face',H),
  m(MU,'Hard','What is Fireboy DML\'s real surname?','Adefolahan','Ogulu','Adeleke','Adefolahan','Balogun',H),
  m(MU,'Hard','Which record label is Fireboy DML signed to?','YBNL','Mavin','YBNL','DMW','Starboy',H),
  m(MU,'Hard','What is Afrobeats producer Sarz\'s real surname?','Ighodaro','Ajereh','Collins','Ighodaro','Adeleke',H),
  m(MU,'Hard','When was Burna Boy\'s first studio album released?','2013','2011','2012','2013','2015',H),
  m(MU,'Hard','What is Yemi Alade\'s debut album called?','King of Queens','Mama Africa','King of Queens','Woman of Steel','Black Magic',H),
  m(MU,'Hard','Which song by Rema broke records on the Billboard Afrobeats chart?','Calm Down','Dumebi','Calm Down','Bounce','FYN',H),
  m(MU,'Hard','Who founded the YBNL music collective?','Olamide','Don Jazzy','Olamide','Davido','Burna Boy',H),

  // =============================================
  // STUDENT CHALLENGE (100)
  // =============================================
  f(ST,'Easy','The chemical symbol for water is ___','H₂O',E),
  f(ST,'Easy','The planet closest to the Sun is ___','Mercury',E),
  f(ST,'Easy','The largest planet in our solar system is ___','Jupiter',E),
  f(ST,'Easy','The process by which plants make their food using sunlight is called ___','Photosynthesis',E),
  f(ST,'Easy','The capital of England is ___','London',E),
  f(ST,'Easy','The freezing point of water is ___ degrees Celsius','0',E),
  f(ST,'Easy','The boiling point of water is ___ degrees Celsius','100',E),
  f(ST,'Easy','The square root of 144 is ___','12',E),
  f(ST,'Easy','The powerhouse of the cell is the ___','Mitochondria',E),
  f(ST,'Easy','The number of continents on Earth is ___','7',E),
  f(ST,'Easy','William Shakespeare is famous for writing ___ and other plays','Romeo and Juliet',E),
  f(ST,'Easy','The longest bone in the human body is the ___','Femur',E),
  f(ST,'Easy','The speed of light is approximately ___ km per second','300,000',E),
  f(ST,'Easy','The chemical symbol for gold is ___','Au',E),
  f(ST,'Easy','2 multiplied by 12 equals ___','24',E),
  f(ST,'Easy','The study of the human body is called ___','Anatomy',E),
  f(ST,'Easy','Oxygen in the periodic table has the atomic number ___','8',E),
  m(ST,'Easy','What is the chemical formula for water?','H₂O','HO','H₂O','H₂O₂','HO₂',E),
  m(ST,'Easy','Which planet is closest to the Sun?','Mercury','Venus','Mercury','Earth','Mars',E),
  m(ST,'Easy','What is the largest planet in the solar system?','Jupiter','Saturn','Jupiter','Neptune','Uranus',E),
  m(ST,'Easy','What is the process by which plants make food using sunlight called?','Photosynthesis','Respiration','Digestion','Photosynthesis','Transpiration',E),
  m(ST,'Easy','What is the capital of England?','London','Manchester','London','Birmingham','Edinburgh',E),
  m(ST,'Easy','At what temperature does water freeze?','0°C','100°C','0°C','-10°C','32°F',E),
  m(ST,'Easy','What is the square root of 144?','12','10','11','12','13',E),
  m(ST,'Easy','What is the powerhouse of the cell?','Mitochondria','Nucleus','Ribosome','Mitochondria','Cell wall',E),
  m(ST,'Easy','How many continents are there on Earth?','7','5','6','7','8',E),
  m(ST,'Easy','Who wrote Romeo and Juliet?','William Shakespeare','Charles Dickens','William Shakespeare','Jane Austen','John Keats',E),
  m(ST,'Easy','What is the longest bone in the human body?','Femur','Tibia','Femur','Spine','Humerus',E),
  m(ST,'Easy','What is the chemical symbol for gold?','Au','Go','Ag','Au','Gd',E),
  m(ST,'Easy','What is 2 multiplied by 12?','24','20','22','24','26',E),
  m(ST,'Easy','What is the study of the human body called?','Anatomy','Biology','Anatomy','Physiology','Zoology',E),

  f(ST,'Medium','The speed of sound in air is approximately ___ meters per second','343',M),
  f(ST,'Medium','The chemical formula for table salt is ___','NaCl',M),
  f(ST,'Medium','The force of attraction between objects with mass is called ___','Gravity',M),
  f(ST,'Medium','DNA stands for ___ Acid','Deoxyribonucleic',M),
  f(ST,'Medium','The study of living organisms is called ___','Biology',M),
  f(ST,'Medium','The atomic number of Carbon is ___','6',M),
  f(ST,'Medium','The French Revolution began in ___','1789',M),
  f(ST,'Medium','The man who invented the telephone was ___','Alexander Graham Bell',M),
  f(ST,'Medium','Newton\'s first law of motion states that an object at rest stays at rest unless acted upon by an external ___','force',M),
  f(ST,'Medium','The chemical element with the symbol Fe is ___','Iron',M),
  f(ST,'Medium','The Pythagorean theorem states that a² + b² = ___','c²',M),
  f(ST,'Medium','The study of rocks and minerals is called ___','Geology',M),
  f(ST,'Medium','The element with atomic number 79 is ___','Gold',M),
  f(ST,'Medium','The process by which living things break down food to release energy is called ___','Respiration',M),
  f(ST,'Medium','The first man to walk on the moon was ___','Neil Armstrong',M),
  f(ST,'Medium','The organ that pumps blood around the human body is the ___','Heart',M),
  f(ST,'Medium','The smallest unit of matter is the ___','Atom',M),
  m(ST,'Medium','What is the chemical formula for table salt?','NaCl','NaOH','NaCl','HCl','KCl',M),
  m(ST,'Medium','What does DNA stand for?','Deoxyribonucleic Acid','Dioxonucleic Acid','Deoxyribonucleic Acid','Deoxyribose Acid','Diribonucleic Acid',M),
  m(ST,'Medium','What is the atomic number of Carbon?','6','4','6','8','12',M),
  m(ST,'Medium','When did the French Revolution begin?','1789','1776','1789','1799','1800',M),
  m(ST,'Medium','Who invented the telephone?','Alexander Graham Bell','Thomas Edison','Nikola Tesla','Alexander Graham Bell','Guglielmo Marconi',M),
  m(ST,'Medium','What does Newton\'s first law describe?','Inertia','Gravity','Inertia','Acceleration','Momentum',M),
  m(ST,'Medium','What is the chemical symbol Fe?','Iron','Fluorine','Iron','Fermium','Francium',M),
  m(ST,'Medium','What does Pythagoras\' theorem state?','a² + b² = c²','a + b = c','a² - b² = c²','a² + b² = c²','a × b = c',M),
  m(ST,'Medium','What is the study of rocks and minerals called?','Geology','Geography','Biology','Geology','Mineralogy',M),
  m(ST,'Medium','What is the element with atomic number 79?','Gold','Silver','Platinum','Gold','Iron',M),
  m(ST,'Medium','Who was the first man to walk on the moon?','Neil Armstrong','Buzz Aldrin','Yuri Gagarin','Neil Armstrong','John Glenn',M),
  m(ST,'Medium','What is the process of releasing energy from food in living things?','Respiration','Photosynthesis','Transpiration','Respiration','Digestion',M),
  m(ST,'Medium','What is the speed of sound in air approximately?','343 m/s','200 m/s','300 m/s','343 m/s','500 m/s',M),
  m(ST,'Medium','What is the smallest unit of matter?','Atom','Molecule','Cell','Atom','Proton',M),

  f(ST,'Hard','The theory of relativity was developed by ___','Albert Einstein',H),
  f(ST,'Hard','The unit of electric current is the ___','Ampere',H),
  f(ST,'Hard','Avogadro\'s number is approximately 6.022 × ___','10²³',H),
  f(ST,'Hard','The process by which a solid changes directly to a gas is called ___','Sublimation',H),
  f(ST,'Hard','The chemical formula for sulphuric acid is ___','H₂SO₄',H),
  f(ST,'Hard','The speed of electromagnetic waves in a vacuum is ___ m/s','3 × 10⁸',H),
  f(ST,'Hard','The second law of thermodynamics is related to ___','Entropy',H),
  f(ST,'Hard','The powerhouse of the cell, the mitochondria, has its own ___ separate from the nucleus','DNA',H),
  f(ST,'Hard','The Krebs cycle takes place in the ___ of the mitochondria','matrix',H),
  f(ST,'Hard','Pi (π) to five decimal places is 3._____','14159',H),
  f(ST,'Hard','The SI unit of force is the ___','Newton',H),
  f(ST,'Hard','The study of the structure and function of cells is called ___','Cytology',H),
  f(ST,'Hard','Charles Darwin published "On the Origin of Species" in ___','1859',H),
  f(ST,'Hard','The human genome contains approximately ___ base pairs','3 billion',H),
  f(ST,'Hard','The lightest element on the periodic table is ___','Hydrogen',H),
  f(ST,'Hard','Ohm\'s law states that voltage equals current multiplied by ___','Resistance',H),
  m(ST,'Hard','Who developed the theory of relativity?','Albert Einstein','Isaac Newton','Albert Einstein','Niels Bohr','Max Planck',H),
  m(ST,'Hard','What is the unit of electric current?','Ampere','Volt','Watt','Ampere','Ohm',H),
  m(ST,'Hard','What is the process of a solid changing directly to a gas?','Sublimation','Evaporation','Condensation','Sublimation','Melting',H),
  m(ST,'Hard','What is the chemical formula for sulphuric acid?','H₂SO₄','HSO₄','H₂SO₃','H₂SO₄','H₂S',H),
  m(ST,'Hard','When did Darwin publish "On the Origin of Species"?','1859','1848','1859','1871','1882',H),
  m(ST,'Hard','What is the SI unit of force?','Newton','Joule','Pascal','Newton','Watt',H),
  m(ST,'Hard','What is the study of the structure of cells called?','Cytology','Histology','Cytology','Anatomy','Physiology',H),
  m(ST,'Hard','Which scientist formulated the law of gravity?','Isaac Newton','Albert Einstein','Isaac Newton','Galileo Galilei','Niels Bohr',H),
  m(ST,'Hard','What is Avogadro\'s number approximately?','6.022 × 10²³','6.022 × 10²¹','6.022 × 10²²','6.022 × 10²³','6.022 × 10²⁴',H),
  m(ST,'Hard','Ohm\'s law states that Voltage = Current × what?','Resistance','Power','Resistance','Capacitance','Frequency',H),
  m(ST,'Hard','What is the lightest element on the periodic table?','Hydrogen','Helium','Hydrogen','Lithium','Carbon',H),
  m(ST,'Hard','The second law of thermodynamics concerns which concept?','Entropy','Energy','Entropy','Enthalpy','Momentum',H),
  m(ST,'Hard','What is pi (π) to two decimal places?','3.14','3.12','3.14','3.15','3.16',H),
  m(ST,'Hard','Krebs cycle takes place in which part of the mitochondria?','Matrix','Inner membrane','Outer membrane','Matrix','Cytoplasm',H),

  // =============================================
  // GEOGRAPHY CHALLENGE (100)
  // =============================================
  f(GE,'Easy','The capital of South Africa\'s government is ___','Pretoria',E),
  f(GE,'Easy','The longest river in the world is the ___','Nile',E),
  f(GE,'Easy','The largest continent by area is ___','Asia',E),
  f(GE,'Easy','The smallest country in the world is ___','Vatican City',E),
  f(GE,'Easy','The capital of France is ___','Paris',E),
  f(GE,'Easy','The capital of Ghana is ___','Accra',E),
  f(GE,'Easy','The tallest mountain in the world is ___','Mount Everest',E),
  f(GE,'Easy','The largest ocean in the world is the ___ Ocean','Pacific',E),
  f(GE,'Easy','The capital of Kenya is ___','Nairobi',E),
  f(GE,'Easy','Africa has ___ countries','54',E),
  f(GE,'Easy','The continent with the most countries is ___','Africa',E),
  f(GE,'Easy','The Amazon River is in ___','South America',E),
  f(GE,'Easy','The capital of Egypt is ___','Cairo',E),
  f(GE,'Easy','The country with the most people in the world is ___','China',E),
  f(GE,'Easy','The Sahara Desert is in ___','Africa',E),
  f(GE,'Easy','The capital of the United States is ___','Washington D.C.',E),
  f(GE,'Easy','The ___ Ocean lies between Africa and the Americas','Atlantic',E),
  m(GE,'Easy','What is the longest river in the world?','Nile','Amazon','Nile','Mississippi','Congo',E),
  m(GE,'Easy','What is the largest continent by area?','Asia','Africa','Asia','Europe','North America',E),
  m(GE,'Easy','What is the smallest country in the world?','Vatican City','Monaco','Vatican City','San Marino','Liechtenstein',E),
  m(GE,'Easy','What is the capital of France?','Paris','Lyon','Marseille','Paris','Nice',E),
  m(GE,'Easy','What is the capital of Ghana?','Accra','Kumasi','Accra','Tamale','Cape Coast',E),
  m(GE,'Easy','What is the tallest mountain in the world?','Mount Everest','Mount Kenya','Mount Kilimanjaro','Mount Everest','Mont Blanc',E),
  m(GE,'Easy','What is the largest ocean in the world?','Pacific Ocean','Atlantic Ocean','Pacific Ocean','Indian Ocean','Arctic Ocean',E),
  m(GE,'Easy','What is the capital of Kenya?','Nairobi','Mombasa','Kampala','Nairobi','Dar es Salaam',E),
  m(GE,'Easy','How many countries are in Africa?','54','48','50','54','60',E),
  m(GE,'Easy','Which continent has the most countries?','Africa','Asia','Europe','Africa','America',E),
  m(GE,'Easy','Where is the Amazon River?','South America','North America','South America','Africa','Asia',E),
  m(GE,'Easy','What is the capital of Egypt?','Cairo','Alexandria','Luxor','Cairo','Aswan',E),
  m(GE,'Easy','What is the most populous country in the world?','China','India','China','USA','Indonesia',E),
  m(GE,'Easy','Which ocean lies between Africa and the Americas?','Atlantic Ocean','Pacific Ocean','Indian Ocean','Atlantic Ocean','Arctic Ocean',E),
  m(GE,'Easy','Where is the Sahara Desert?','Africa','Asia','Middle East','Africa','Australia',E),

  f(GE,'Medium','The capital of Ethiopia is ___','Addis Ababa',M),
  f(GE,'Medium','The capital of Tanzania is ___','Dodoma',M),
  f(GE,'Medium','Lake Victoria is the largest lake in ___','Africa',M),
  f(GE,'Medium','The Great Rift Valley runs through ___','East Africa',M),
  f(GE,'Medium','The River Congo is the deepest river in the ___','world',M),
  f(GE,'Medium','The capital of Brazil is ___','Brasília',M),
  f(GE,'Medium','The country with the longest coastline in the world is ___','Canada',M),
  f(GE,'Medium','Mount Kilimanjaro is the highest mountain in ___','Africa',M),
  f(GE,'Medium','The Tropic of Cancer passes through ___ in Africa','North Africa',M),
  f(GE,'Medium','The capital of Senegal is ___','Dakar',M),
  f(GE,'Medium','The country of Nigeria has a coastline on the ___ Gulf','Guinea',M),
  f(GE,'Medium','The international date line is at ___ degrees longitude','180',M),
  f(GE,'Medium','The most populous city in Africa is ___','Lagos',M),
  f(GE,'Medium','The ___ Strait separates Africa from Europe','Gibraltar',M),
  f(GE,'Medium','The capital of Cameroon is ___','Yaoundé',M),
  f(GE,'Medium','The River Niger originates from the hills of ___','Guinea',M),
  f(GE,'Medium','The landlocked country in East Africa that has no coastline is ___','Uganda',M),
  m(GE,'Medium','What is the capital of Ethiopia?','Addis Ababa','Kampala','Nairobi','Addis Ababa','Khartoum',M),
  m(GE,'Medium','What is the capital of Tanzania?','Dodoma','Dar es Salaam','Dodoma','Mombasa','Nairobi',M),
  m(GE,'Medium','What is the largest lake in Africa?','Lake Victoria','Lake Tanganyika','Lake Victoria','Lake Malawi','Lake Chad',M),
  m(GE,'Medium','The Great Rift Valley runs through which part of Africa?','East Africa','West Africa','East Africa','North Africa','Southern Africa',M),
  m(GE,'Medium','What is the world\'s deepest river?','Congo River','Amazon River','Nile River','Congo River','Mississippi River',M),
  m(GE,'Medium','What is the capital of Brazil?','Brasília','São Paulo','Rio de Janeiro','Brasília','Manaus',M),
  m(GE,'Medium','Which country has the longest coastline in the world?','Canada','Australia','Russia','Canada','USA',M),
  m(GE,'Medium','Where is Mount Kilimanjaro?','Tanzania','Kenya','Tanzania','Ethiopia','Uganda',M),
  m(GE,'Medium','What is the capital of Senegal?','Dakar','Abidjan','Accra','Dakar','Lomé',M),
  m(GE,'Medium','What strait separates Africa from Europe?','Strait of Gibraltar','Suez Canal','Strait of Gibraltar','Bosphorus Strait','Strait of Hormuz',M),
  m(GE,'Medium','What is the capital of Cameroon?','Yaoundé','Douala','Yaoundé','Bamenda','Buea',M),
  m(GE,'Medium','Where does the Niger River originate?','Guinea','Mali','Guinea','Nigeria','Niger',M),
  m(GE,'Medium','What is the most populous city in Africa?','Lagos','Cairo','Lagos','Johannesburg','Kinshasa',M),
  m(GE,'Medium','The international date line is at how many degrees longitude?','180°','90°','150°','180°','270°',M),

  f(GE,'Hard','The Tropic of Capricorn passes through ___ countries in Africa','6',H),
  f(GE,'Hard','The deepest lake in the world is Lake ___','Baikal',H),
  f(GE,'Hard','The population of Africa is estimated at over ___ billion people','1.4',H),
  f(GE,'Hard','The country with the most pyramids in the world is ___','Sudan',H),
  f(GE,'Hard','The capital of the Democratic Republic of Congo is ___','Kinshasa',H),
  f(GE,'Hard','The equator passes through ___ African countries','6',H),
  f(GE,'Hard','The highest point in Nigeria is Chappal ___ at 2,419 metres','Waddi',H),
  f(GE,'Hard','The Ring of Fire is a zone of volcanic activity around the ___ Ocean','Pacific',H),
  f(GE,'Hard','The country with the most time zones in the world is ___','France',H),
  f(GE,'Hard','The capital of Mozambique is ___','Maputo',H),
  f(GE,'Hard','The Nile River passes through ___ countries','11',H),
  f(GE,'Hard','The Suez Canal connects the Mediterranean Sea to the ___ Sea','Red',H),
  f(GE,'Hard','The country of Lesotho is entirely surrounded by ___','South Africa',H),
  f(GE,'Hard','The island country off the coast of East Africa known for its vanilla is ___','Madagascar',H),
  f(GE,'Hard','The highest active volcano in Africa is ___ in the DRC','Nyiragongo',H),
  f(GE,'Hard','The Strait of Malacca separates the Malay Peninsula from ___','Sumatra',H),
  m(GE,'Hard','What is the deepest lake in the world?','Lake Baikal','Lake Victoria','Lake Tanganyika','Lake Baikal','Lake Superior',H),
  m(GE,'Hard','Which country has the most pyramids in the world?','Sudan','Egypt','Sudan','Libya','Morocco',H),
  m(GE,'Hard','What is the capital of the Democratic Republic of Congo?','Kinshasa','Brazzaville','Kinshasa','Lubumbashi','Kisangani',H),
  m(GE,'Hard','How many countries does the equator pass through in Africa?','6','4','5','6','7',H),
  m(GE,'Hard','What is Nigeria\'s highest peak called?','Chappal Waddi','Obudu Plateau','Chappal Waddi','Biu Plateau','Mandara Mountains',H),
  m(GE,'Hard','Which ocean does the Ring of Fire surround?','Pacific Ocean','Atlantic Ocean','Indian Ocean','Pacific Ocean','Arctic Ocean',H),
  m(GE,'Hard','Which country has the most time zones?','France','Russia','USA','France','China',H),
  m(GE,'Hard','What is the capital of Mozambique?','Maputo','Beira','Maputo','Nampula','Pemba',H),
  m(GE,'Hard','Through how many countries does the Nile River flow?','11','7','9','11','13',H),
  m(GE,'Hard','What does the Suez Canal connect the Mediterranean Sea to?','Red Sea','Arabian Sea','Red Sea','Persian Gulf','Indian Ocean',H),
  m(GE,'Hard','Which country is completely surrounded by South Africa?','Lesotho','Eswatini','Lesotho','Zimbabwe','Namibia',H),
  m(GE,'Hard','What is the highest active volcano in Africa?','Nyiragongo','Kilimanjaro','Nyiragongo','Mount Kenya','Mount Cameroon',H),
  m(GE,'Hard','How high is Nigeria\'s highest peak, Chappal Waddi?','2,419 metres','1,500 metres','2,000 metres','2,419 metres','3,000 metres',H),
  m(GE,'Hard','Which island off East Africa is known for vanilla production?','Madagascar','Mauritius','Madagascar','Seychelles','Comoros',H),

  // =============================================
  // BIBLE CHALLENGE (100)
  // =============================================
  f(BI,'Easy','The first book of the Bible is ___','Genesis',E),
  f(BI,'Easy','The last book of the Bible is ___','Revelation',E),
  f(BI,'Easy','Jesus was born in ___','Bethlehem',E),
  f(BI,'Easy','The Bible has ___ Testaments','2',E),
  f(BI,'Easy','Moses parted the ___ Sea to lead the Israelites','Red',E),
  f(BI,'Easy','David killed the giant ___ with a sling and stone','Goliath',E),
  f(BI,'Easy','Noah built an ___ to survive the great flood','Ark',E),
  f(BI,'Easy','The mother of Jesus is ___','Mary',E),
  f(BI,'Easy','Jesus had ___ disciples','12',E),
  f(BI,'Easy','The first man created by God according to the Bible was ___','Adam',E),
  f(BI,'Easy','The first woman in the Bible was ___','Eve',E),
  f(BI,'Easy','Jesus was baptised by ___','John the Baptist',E),
  f(BI,'Easy','The Garden of Eden is mentioned in the book of ___','Genesis',E),
  f(BI,'Easy','King Solomon was the son of King ___','David',E),
  f(BI,'Easy','The shortest verse in the Bible is "___ wept"','Jesus',E),
  f(BI,'Easy','Jesus fed 5,000 people with ___ loaves and two fish','five',E),
  f(BI,'Easy','Samson\'s strength lay in his ___','hair',E),
  m(BI,'Easy','What is the first book of the Bible?','Genesis','Exodus','Psalms','Genesis','Proverbs',E),
  m(BI,'Easy','What is the last book of the Bible?','Revelation','Jude','Malachi','Revelation','Acts',E),
  m(BI,'Easy','Where was Jesus born?','Bethlehem','Nazareth','Jerusalem','Bethlehem','Jericho',E),
  m(BI,'Easy','How many testaments does the Bible have?','2','1','2','3','4',E),
  m(BI,'Easy','Who did David kill with a stone and sling?','Goliath','Saul','Absalom','Goliath','Samson',E),
  m(BI,'Easy','What did Noah build to survive the flood?','An Ark','A boat','An Ark','A raft','A ship',E),
  m(BI,'Easy','Who is the mother of Jesus?','Mary','Martha','Mary Magdalene','Mary','Elizabeth',E),
  m(BI,'Easy','How many disciples did Jesus have?','12','7','10','12','14',E),
  m(BI,'Easy','Who was the first man God created?','Adam','Noah','Cain','Adam','Abel',E),
  m(BI,'Easy','Which sea did Moses part?','Red Sea','Dead Sea','Sea of Galilee','Red Sea','Mediterranean Sea',E),
  m(BI,'Easy','Who baptised Jesus?','John the Baptist','Peter','John the Baptist','James','Andrew',E),
  m(BI,'Easy','What was the source of Samson\'s strength?','His hair','His muscles','His sword','His hair','His faith',E),
  m(BI,'Easy','Who was Solomon\'s father?','King David','King Saul','King David','King Solomon','Abraham',E),
  m(BI,'Easy','How many loaves did Jesus use to feed 5,000 people?','5','2','3','5','7',E),

  f(BI,'Medium','The disciple who betrayed Jesus was ___','Judas Iscariot',M),
  f(BI,'Medium','The longest book in the Bible is ___','Psalms',M),
  f(BI,'Medium','The book of Psalms is largely attributed to King ___','David',M),
  f(BI,'Medium','Jonah was swallowed by a large ___ in the Bible','fish',M),
  f(BI,'Medium','Paul was originally called ___ before his conversion','Saul',M),
  f(BI,'Medium','The Tower of ___ was built by people trying to reach heaven','Babel',M),
  f(BI,'Medium','Joseph was sold into slavery by his ___ brothers','11',M),
  f(BI,'Medium','The Ten Commandments were given to Moses on Mount ___','Sinai',M),
  f(BI,'Medium','Elijah the prophet was taken up to heaven in a ___ of fire','chariot',M),
  f(BI,'Medium','John 3:16 says "For God so loved the world that he gave his ___ son"','only',M),
  f(BI,'Medium','The book of Ruth tells the story of a ___ woman who followed her mother-in-law','Moabite',M),
  f(BI,'Medium','The Sermon on the Mount is found in the Gospel of ___','Matthew',M),
  f(BI,'Medium','Peter denied Jesus ___ times before the rooster crowed','three',M),
  f(BI,'Medium','The three wise men (Magi) brought Jesus gifts of gold, frankincense, and ___','myrrh',M),
  f(BI,'Medium','Lazarus was raised from the dead by ___','Jesus',M),
  f(BI,'Medium','The book of ___ is the last book of the Old Testament','Malachi',M),
  f(BI,'Medium','Abraham\'s wife who bore Isaac was called ___','Sarah',M),
  m(BI,'Medium','Who betrayed Jesus for 30 pieces of silver?','Judas Iscariot','Peter','Thomas','Judas Iscariot','Pontius Pilate',M),
  m(BI,'Medium','What is the longest book in the Bible?','Psalms','Genesis','Isaiah','Psalms','Jeremiah',M),
  m(BI,'Medium','What was Paul called before his conversion?','Saul','Simon','Cornelius','Saul','Barnabas',M),
  m(BI,'Medium','What was the Tower of Babel built for?','To reach heaven','To fight God','To reach heaven','To store grain','To see the stars',M),
  m(BI,'Medium','How many brothers did Joseph have?','11','9','10','11','12',M),
  m(BI,'Medium','On which mountain were the Ten Commandments given?','Mount Sinai','Mount Carmel','Mount Zion','Mount Sinai','Mount Ararat',M),
  m(BI,'Medium','How was Elijah taken to heaven?','Chariot of fire','On a cloud','Chariot of fire','By angels','He walked',M),
  m(BI,'Medium','What does John 3:16 say God gave?','His only begotten Son','His Spirit','His only begotten Son','His angels','His Kingdom',M),
  m(BI,'Medium','The Sermon on the Mount is found in which Gospel?','Matthew','Mark','Luke','Matthew','John',M),
  m(BI,'Medium','How many times did Peter deny Jesus?','3','1','2','3','4',M),
  m(BI,'Medium','What gifts did the wise men bring Jesus?','Gold, frankincense, myrrh','Gold, silver, bronze','Gold, frankincense, myrrh','Oil, wine, bread','Gold, oil, spices',M),
  m(BI,'Medium','Who raised Lazarus from the dead?','Jesus','Elijah','Elisha','Jesus','Peter',M),
  m(BI,'Medium','What is the last book of the Old Testament?','Malachi','Haggai','Zechariah','Malachi','Revelation',M),
  m(BI,'Medium','Who was Abraham\'s wife?','Sarah','Hagar','Rebekah','Sarah','Rachel',M),

  f(BI,'Hard','The book of Lamentations was written by ___','Jeremiah',H),
  f(BI,'Hard','The Hebrew word "Amen" means ___','So be it',H),
  f(BI,'Hard','Methuselah is recorded as the oldest person in the Bible, living ___ years','969',H),
  f(BI,'Hard','The Bible was originally written in Hebrew, Aramaic, and ___','Greek',H),
  f(BI,'Hard','Paul wrote ___ letters (epistles) in the New Testament','13',H),
  f(BI,'Hard','The king who ordered all baby boys under 2 killed was King ___','Herod',H),
  f(BI,'Hard','The walls of ___ fell after Israel marched around them seven times','Jericho',H),
  f(BI,'Hard','The Apostle Paul was a tent-maker from the city of ___','Tarsus',H),
  f(BI,'Hard','The book of Proverbs is largely attributed to King ___','Solomon',H),
  f(BI,'Hard','The prophet who was taken to heaven without dying was ___','Enoch',H),
  f(BI,'Hard','The number of plagues that God sent on Egypt was ___','10',H),
  f(BI,'Hard','Absalom was the rebellious son of King ___','David',H),
  f(BI,'Hard','In the book of Job, God allowed ___ to test Job','Satan',H),
  f(BI,'Hard','The shortest book in the Old Testament is ___','Obadiah',H),
  f(BI,'Hard','The number of chapters in the book of Psalms is ___','150',H),
  f(BI,'Hard','Ruth\'s mother-in-law was called ___','Naomi',H),
  m(BI,'Hard','Who wrote the book of Lamentations?','Jeremiah','Isaiah','Ezekiel','Jeremiah','Daniel',H),
  m(BI,'Hard','How old was Methuselah when he died?','969','900','969','777','800',H),
  m(BI,'Hard','In how many languages was the Bible originally written?','3','1','2','3','4',H),
  m(BI,'Hard','How many epistles did Paul write in the New Testament?','13','7','10','13','15',H),
  m(BI,'Hard','Which king ordered the killing of all baby boys?','King Herod','King Pharaoh','King Herod','King Saul','King Solomon',H),
  m(BI,'Hard','How many times did Israel march around Jericho before the walls fell?','7','3','5','7','10',H),
  m(BI,'Hard','Where was the Apostle Paul from?','Tarsus','Jerusalem','Antioch','Tarsus','Athens',H),
  m(BI,'Hard','Who is largely credited with writing Proverbs?','Solomon','David','Moses','Solomon','Isaiah',H),
  m(BI,'Hard','How many plagues did God send on Egypt?','10','7','9','10','12',H),
  m(BI,'Hard','Who was King David\'s rebellious son?','Absalom','Solomon','Amnon','Absalom','Adonijah',H),
  m(BI,'Hard','What is the shortest book in the Old Testament?','Obadiah','Haggai','Philemon','Obadiah','Nahum',H),
  m(BI,'Hard','How many chapters are in the book of Psalms?','150','120','150','180','200',H),
  m(BI,'Hard','What was Naomi\'s relationship to Ruth?','Mother-in-law','Mother','Aunt','Mother-in-law','Sister',H),
  m(BI,'Hard','Which prophet was taken to heaven without dying?','Enoch','Elijah','Moses','Enoch','Isaiah',H),
  m(BI,'Hard','In the book of Job, who was allowed to test Job?','Satan','God\'s angel','Satan','A demon','Eliphaz',H),

  // =============================================
  // AI & TECHNOLOGY CHALLENGE (100)
  // =============================================
  f(AI,'Easy','The company that makes the iPhone is ___','Apple',E),
  f(AI,'Easy','WWW stands for World Wide ___','Web',E),
  f(AI,'Easy','Google is owned by the parent company called ___','Alphabet',E),
  f(AI,'Easy','The social media platform for short videos, popular with Gen Z, is ___','TikTok',E),
  f(AI,'Easy','WhatsApp was bought by ___ in 2014','Facebook',E),
  f(AI,'Easy','The programming language known as the language of the web is ___','JavaScript',E),
  f(AI,'Easy','The most popular search engine in the world is ___','Google',E),
  f(AI,'Easy','AI stands for Artificial ___','Intelligence',E),
  f(AI,'Easy','The storage unit larger than a Gigabyte is called a ___','Terabyte',E),
  f(AI,'Easy','The CEO of Tesla and SpaceX is ___','Elon Musk',E),
  f(AI,'Easy','Wi-Fi is a technology for ___ internet connection','wireless',E),
  f(AI,'Easy','The app store for Android phones is called ___ Play','Google',E),
  f(AI,'Easy','PDF stands for Portable ___ Format','Document',E),
  f(AI,'Easy','Microsoft was founded by Bill ___ and Paul Allen','Gates',E),
  f(AI,'Easy','The "E" in email stands for ___','Electronic',E),
  f(AI,'Easy','Facebook was founded by Mark ___','Zuckerberg',E),
  f(AI,'Easy','The Nigerian tech hub city known for its startup ecosystem is ___','Lagos',E),
  m(AI,'Easy','Which company makes the iPhone?','Apple','Samsung','Apple','Nokia','Huawei',E),
  m(AI,'Easy','What does WWW stand for?','World Wide Web','World Wide Web','World Wire Web','Worldwide Web','Wide World Web',E),
  m(AI,'Easy','Who owns Google?','Alphabet Inc.','Microsoft','Alphabet Inc.','Apple','Amazon',E),
  m(AI,'Easy','Which platform is known for short videos popular with Gen Z?','TikTok','Instagram','YouTube','TikTok','Snapchat',E),
  m(AI,'Easy','Who bought WhatsApp in 2014?','Facebook','Google','Apple','Facebook','Microsoft',E),
  m(AI,'Easy','What is the most popular search engine?','Google','Bing','Google','Yahoo','DuckDuckGo',E),
  m(AI,'Easy','What does AI stand for?','Artificial Intelligence','Automated Intelligence','Artificial Intelligence','Advanced Integration','Automated Internet',E),
  m(AI,'Easy','Who is the CEO of Tesla?','Elon Musk','Jeff Bezos','Elon Musk','Tim Cook','Mark Zuckerberg',E),
  m(AI,'Easy','What storage unit comes after a Gigabyte?','Terabyte','Megabyte','Gigabyte','Terabyte','Petabyte',E),
  m(AI,'Easy','What does PDF stand for?','Portable Document Format','Portable Data File','Personal Document Format','Portable Document Format','Personal Data Format',E),
  m(AI,'Easy','Who co-founded Microsoft?','Bill Gates','Steve Jobs','Bill Gates','Mark Zuckerberg','Larry Page',E),
  m(AI,'Easy','Who founded Facebook?','Mark Zuckerberg','Bill Gates','Steve Jobs','Mark Zuckerberg','Larry Page',E),
  m(AI,'Easy','What is the Android app store called?','Google Play','App Store','Google Play','Play Market','Android Store',E),
  m(AI,'Easy','What does "E" stand for in email?','Electronic','Express','Electronic','Easy','Ethernet',E),

  f(AI,'Medium','The AI chatbot created by OpenAI is called ___','ChatGPT',M),
  f(AI,'Medium','The programming language created by Guido van Rossum is ___','Python',M),
  f(AI,'Medium','The Nigerian fintech company Flutterwave was founded in ___','2016',M),
  f(AI,'Medium','The cloud computing service from Amazon is called ___','AWS',M),
  f(AI,'Medium','The operating system developed by Microsoft is ___','Windows',M),
  f(AI,'Medium','Blockchain technology was first introduced with ___','Bitcoin',M),
  f(AI,'Medium','The most popular open-source operating system is ___','Linux',M),
  f(AI,'Medium','Andela is a Nigerian tech company that trains ___ across Africa','software developers',M),
  f(AI,'Medium','HTTP stands for HyperText ___ Protocol','Transfer',M),
  f(AI,'Medium','The Nigerian payment platform founded by Shola Akinlade is ___','Paystack',M),
  f(AI,'Medium','RAM stands for Random Access ___','Memory',M),
  f(AI,'Medium','The first iPhone was launched in ___','2007',M),
  f(AI,'Medium','The programming language commonly used for web styling is ___','CSS',M),
  f(AI,'Medium','The largest e-commerce company in the world is ___','Amazon',M),
  f(AI,'Medium','The Nigerian app "Kuda" is a digital ___','bank',M),
  f(AI,'Medium','GPT in ChatGPT stands for Generative Pre-trained ___','Transformer',M),
  f(AI,'Medium','The social media platform X was formerly known as ___','Twitter',M),
  m(AI,'Medium','Which AI chatbot was created by OpenAI?','ChatGPT','Gemini','Bard','ChatGPT','Claude',M),
  m(AI,'Medium','Which programming language did Guido van Rossum create?','Python','Java','Python','Ruby','Perl',M),
  m(AI,'Medium','What year was Flutterwave founded?','2016','2012','2014','2016','2018',M),
  m(AI,'Medium','What is Amazon\'s cloud computing service called?','AWS','Azure','AWS','Google Cloud','IBM Cloud',M),
  m(AI,'Medium','Blockchain technology was first introduced with what?','Bitcoin','Ethereum','Bitcoin','NFTs','DeFi',M),
  m(AI,'Medium','What is the most popular open-source operating system?','Linux','Windows','macOS','Linux','Android',M),
  m(AI,'Medium','What does HTTP stand for?','HyperText Transfer Protocol','HyperText Transfer Protocol','HyperText Transmission Protocol','High Transfer Text Protocol','Hyperlink Transfer Protocol',M),
  m(AI,'Medium','Which Nigerian company founded by Shola Akinlade was acquired by Stripe?','Paystack','Flutterwave','Paystack','Kuda','Piggybank',M),
  m(AI,'Medium','What does RAM stand for?','Random Access Memory','Read Access Memory','Random Access Memory','Read Accessible Memory','Rapid Access Memory',M),
  m(AI,'Medium','When was the first iPhone launched?','2007','2005','2006','2007','2008',M),
  m(AI,'Medium','What does GPT stand for in ChatGPT?','Generative Pre-trained Transformer','General Purpose Technology','Generative Pre-trained Transformer','General Processing Tool','Global Pre-trained Technology',M),
  m(AI,'Medium','What was X (formerly) called?','Twitter','Facebook','Instagram','Twitter','Snapchat',M),
  m(AI,'Medium','Which programming language is used for web styling?','CSS','HTML','CSS','JavaScript','Python',M),
  m(AI,'Medium','What type of service is Nigeria\'s Kuda?','Digital bank','Ride-hailing','Social media','Digital bank','E-commerce',M),

  f(AI,'Hard','The company that created the Claude AI assistant is ___','Anthropic',H),
  f(AI,'Hard','The programming language created by James Gosling at Sun Microsystems is ___','Java',H),
  f(AI,'Hard','Moore\'s Law states that the number of transistors on a chip doubles every ___ years','two',H),
  f(AI,'Hard','The Nigerian tech entrepreneur who co-founded Paystack is ___','Shola Akinlade',H),
  f(AI,'Hard','The concept of a neural network in AI is inspired by the human ___','brain',H),
  f(AI,'Hard','The programming paradigm where functions are first-class citizens is called ___ programming','functional',H),
  f(AI,'Hard','SQL stands for Structured ___ Language','Query',H),
  f(AI,'Hard','The Internet protocol that assigns unique addresses to devices is called ___','IP (Internet Protocol)',H),
  f(AI,'Hard','The first general-purpose electronic computer was called ___','ENIAC',H),
  f(AI,'Hard','Nigeria\'s "Silicon Lagoon" is the tech cluster found in ___','Yaba, Lagos',H),
  f(AI,'Hard','The CEO of Anthropic, the company behind Claude AI, is ___','Dario Amodei',H),
  f(AI,'Hard','The concept of machine learning uses ___ data to improve performance','training',H),
  f(AI,'Hard','The term "algorithm" in computing is named after the mathematician Al-___','Khwarizmi',H),
  f(AI,'Hard','Git was created by ___ for version control of the Linux kernel','Linus Torvalds',H),
  f(AI,'Hard','The number system used by computers at its lowest level is ___','binary',H),
  f(AI,'Hard','The Nigerian startup Interswitch was founded in ___','2002',H),
  m(AI,'Hard','Which company created the Claude AI assistant?','Anthropic','OpenAI','Google','Anthropic','Microsoft',H),
  m(AI,'Hard','Who created the Java programming language?','James Gosling','Linus Torvalds','James Gosling','Guido van Rossum','Dennis Ritchie',H),
  m(AI,'Hard','Moore\'s Law says transistor count doubles approximately every how many years?','2 years','1 year','2 years','3 years','5 years',H),
  m(AI,'Hard','Who co-founded Paystack?','Shola Akinlade','Tunde Kehinde','Shola Akinlade','Mitchell Elegbe','Jason Njoku',H),
  m(AI,'Hard','What is AI\'s neural network inspired by?','The human brain','The internet','The human brain','A calculator','A chess engine',H),
  m(AI,'Hard','What does SQL stand for?','Structured Query Language','Sequential Query Language','Structured Query Language','System Query Language','Structured Question Language',H),
  m(AI,'Hard','What was the first general-purpose electronic computer called?','ENIAC','UNIVAC','ENIAC','HAL 9000','IBM 360',H),
  m(AI,'Hard','Nigeria\'s tech cluster known as "Silicon Lagoon" is in which area?','Yaba, Lagos','Victoria Island','Yaba, Lagos','Lekki','Ikeja',H),
  m(AI,'Hard','Who is the CEO of Anthropic?','Dario Amodei','Sam Altman','Dario Amodei','Sundar Pichai','Demis Hassabis',H),
  m(AI,'Hard','Who created Git?','Linus Torvalds','James Gosling','Linus Torvalds','Guido van Rossum','Dennis Ritchie',H),
  m(AI,'Hard','What number system do computers use at their lowest level?','Binary','Decimal','Hexadecimal','Binary','Octal',H),
  m(AI,'Hard','When was Nigerian startup Interswitch founded?','2002','1998','2000','2002','2005',H),
  m(AI,'Hard','What type of programming treats functions as first-class citizens?','Functional programming','Object-oriented programming','Procedural programming','Functional programming','Imperative programming',H),
  m(AI,'Hard','The term "algorithm" is named after which mathematician?','Al-Khwarizmi','Al-Biruni','Al-Khwarizmi','Euclid','Fibonacci',H),

  // === OGUN STATE extra (to reach 100) ===
  f(OG,'Easy','The state that borders Ogun State to the east is ___ State','Ondo',E),
  m(OG,'Easy','Which state borders Ogun State to the east?','Ondo State','Osun State','Ekiti State','Ondo State','Oyo State',E),
  m(OG,'Medium','Which Ogun State town is a major ceramic and pottery production centre?','Ikorodu','Ilaro','Sagamu','Ikorodu','Ota',M),

  // === NIGERIA CHALLENGE extra (to reach 100) ===
  f(NG,'Easy','The Nigerian coat of arms features a black ___ on a white shield','Eagle',E),
  m(NG,'Easy','What animal is on Nigeria\'s coat of arms?','Eagle','Lion','Horse','Eagle','Bull',E),
  m(NG,'Medium','What does WAEC stand for?','West African Examinations Council','West African Examinations Council','West Africa Exam Commission','Western African Education Council','West African Education Committee',M),
  m(NG,'Hard','Which year was Nigeria\'s current national anthem adopted?','1978','1960','1970','1978','1999',H),

  // === SPORTS CHALLENGE extra (to reach 100) ===
  f(SP,'Easy','In football, the goalkeeper is the only player who can use their ___ in the penalty area','hands',E),
  m(SP,'Easy','In basketball, how many points is a three-pointer worth?','3','1','2','3','4',E),
  m(SP,'Medium','Which Nigerian athlete won Olympic bronze in the long jump at the 2020 Tokyo Olympics?','Ese Brume','Blessing Okagbare','Ese Brume','Tobi Amusan','Chioma Onyekwere',M),
  m(SP,'Medium','Which club did Victor Moses play for after Chelsea?','Inter Milan','PSG','Inter Milan','Fenerbahce','Liverpool',M),
  m(SP,'Hard','How many yellow cards equal a red card in football?','2','1','2','3','4',H),
  m(SP,'Hard','Nigeria\'s Enyimba FC won the African Champions League how many consecutive times?','2','1','2','3','4',H),

  // === MUSIC CHALLENGE extra (to reach 100) ===
  f(MU,'Easy','The famous Nigerian gospel musician known as "The Anointed" is Sinach whose hit song is "___ Knows My Name"','Way Maker',E),
  m(MU,'Easy','Simi\'s breakthrough song was?','Tiff','Joromi','Tiff','Original Baby','Love Don\'t Lie',E),
  m(MU,'Medium','Which year was Davido\'s debut EP "Cousin Dave" released?','2011','2010','2011','2012','2013',M),
  m(MU,'Medium','What is Wizkid\'s record label called?','Starboy Entertainment','DMW','Starboy Entertainment','Mavin','YBNL',M),
  m(MU,'Hard','Fela Kuti\'s father was the first president of which Nigerian institution?','Nigerian Baptist Convention','Nigerian Bar Association','Nigerian Baptist Convention','Nigerian Medical Association','Nigerian Union of Teachers',H),
  m(MU,'Hard','Which Nigerian musician was the first to perform at Coachella?','Burna Boy','Wizkid','Burna Boy','Davido','Yemi Alade',H),
  m(MU,'Hard','Tiwa Savage\'s ex-husband Teebillz\'s real name is?','Ayodeji Balogun','Tunji Balogun','Ayodeji Balogun','Tunde Balogun','Adewale Balogun',H),

  // === STUDENT CHALLENGE extra (to reach 100) ===
  f(ST,'Easy','The human body has ___ bones in total','206',E),
  m(ST,'Easy','What is 15% of 200?','30','20','25','30','35',E),
  m(ST,'Medium','What is the chemical symbol for Silver?','Ag','Si','Ag','Sr','Sn',M),
  m(ST,'Medium','What type of triangle has all three sides equal?','Equilateral','Isosceles','Equilateral','Scalene','Right-angled',M),
  m(ST,'Hard','What is the powerhouse of the cell?','Mitochondria','Ribosome','Nucleus','Mitochondria','Cell membrane',H),
  m(ST,'Hard','What is the formula for kinetic energy?','½mv²','mv','½mv²','ma','mv²',H),
  m(ST,'Hard','The study of earthquakes is called?','Seismology','Geology','Seismology','Vulcanology','Meteorology',H),
  m(ST,'Hard','What is the chemical formula for ammonia?','NH₃','NH₄','NO₃','NH₃','N₂H₄',H),

  // === GEOGRAPHY CHALLENGE extra (to reach 100) ===
  f(GE,'Easy','The capital of China is ___','Beijing',E),
  m(GE,'Easy','What is the capital of Australia?','Canberra','Sydney','Melbourne','Canberra','Brisbane',E),
  m(GE,'Medium','What is the capital of Morocco?','Rabat','Casablanca','Marrakech','Rabat','Fez',M),
  m(GE,'Medium','Which African country is known as the "Land of a Thousand Hills"?','Rwanda','Cameroon','Ethiopia','Rwanda','Uganda',M),
  m(GE,'Hard','What is the capital of Angola?','Luanda','Kinshasa','Windhoek','Luanda','Harare',H),
  m(GE,'Hard','Which is the smallest country in Africa?','Seychelles','Djibouti','Sao Tome','Seychelles','Gambia',H),
  m(GE,'Hard','What is the population of Lagos estimated at as of 2023?','Over 15 million','5 million','10 million','Over 15 million','25 million',H),

  // === BIBLE CHALLENGE extra (to reach 100) ===
  f(BI,'Easy','The dove that Noah sent out returned with an olive ___','branch',E),
  m(BI,'Easy','Who replaced Judas Iscariot as the 12th apostle?','Matthias','Barnabas','Matthias','Stephen','Timothy',E),
  m(BI,'Medium','In which city did Paul preach and later stand trial before Caesar?','Rome','Athens','Antioch','Rome','Corinth',M),
  m(BI,'Medium','How long did Jonah stay inside the great fish?','3 days and 3 nights','1 day','7 days','3 days and 3 nights','40 days',M),
  m(BI,'Hard','How many books are in the New Testament?','27','24','27','30','39',H),
  m(BI,'Hard','Which book of the Bible records the giving of the Ten Commandments first?','Exodus','Deuteronomy','Leviticus','Exodus','Numbers',H),
  m(BI,'Hard','How many chapters are in the book of Isaiah?','66','40','52','66','70',H),

  // === AI & TECHNOLOGY extra (to reach 100) ===
  f(AI,'Easy','The full form of USB is Universal ___ Bus','Serial',E),
  m(AI,'Easy','What does URL stand for?','Uniform Resource Locator','Uniform Resource Locator','Universal Resource Link','Uniform Record Locator','United Resource Line',E),
  m(AI,'Medium','Which Nigerian founded the e-commerce company Jumia?','Tunde Kehinde','Jason Njoku','Shola Akinlade','Tunde Kehinde','Mitchell Elegbe',M),
  m(AI,'Medium','What programming language is primarily used for iOS app development?','Swift','Java','Swift','Python','Kotlin',M),
  m(AI,'Hard','What does API stand for?','Application Programming Interface','Application Programming Interface','Automated Processing Interface','Advanced Program Integration','Application Protocol Interface',H),
  m(AI,'Hard','Who invented the World Wide Web in 1989?','Tim Berners-Lee','Bill Gates','Tim Berners-Lee','Steve Jobs','Vint Cerf',H),
  m(AI,'Hard','The Nigerian company Interswitch\'s CEO is?','Mitchell Elegbe','Shola Akinlade','Tunde Kehinde','Mitchell Elegbe','Jason Njoku',H),
  m(AI,'Hard','What does IoT stand for?','Internet of Things','Internet of Things','Integration of Technology','Interface of Things','Internet of Transfers',H),
];
